#!/bin/sh
#
# @name Morphing Bird V1
#
# @type Bionic Bird
# @class Plane

# @output Motor1 Thrust Motor
# @output Servo1 Left Shoulder
# @output Servo2 Left Wrist
# @output Servo3 Right Shoulder
# @output Servo4 Right Wrist
# @output Servo5 Tail Pitch
# @output Servo6 Tail Roll
# @output Servo7 Left Tail Extend
# @output Servo8 Right Tail Extend
#
# @maintainer Zhihua Zhao <aslan.zhao@gmail.com>
#
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mb_defaults

# airframe is morphing bird, referring /src/modules/controll_allocator/module.yaml
param set-default CA_AIRFRAME 14

# thrust motor
param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_PX 0.15
# servos
param set-default CA_SV_CS_COUNT 8
param set-default PWM_AUX_TIM0 50
param set-default PWM_AUX_TIM1 50
param set-default PWM_AUX_TIM2 50
param set-default PWM_AUX_MIN1 500
param set-default PWM_AUX_MIN2 500
param set-default PWM_AUX_MIN3 500
param set-default PWM_AUX_MIN4 500
param set-default PWM_AUX_MIN5 500
param set-default PWM_AUX_MIN6 500
param set-default PWM_AUX_MIN7 500
param set-default PWM_AUX_MIN8 500
param set-default PWM_AUX_MAX1 2500
param set-default PWM_AUX_MAX2 2500
param set-default PWM_AUX_MAX3 2500
param set-default PWM_AUX_MAX4 2500
param set-default PWM_AUX_MAX5 2500
param set-default PWM_AUX_MAX6 2500
param set-default PWM_AUX_MAX7 2500
param set-default PWM_AUX_MAX8 2500
param set-default PWM_AUX_DIS1 500
param set-default PWM_AUX_DIS2 500
param set-default PWM_AUX_DIS3 500
param set-default PWM_AUX_DIS4 500
param set-default PWM_AUX_DIS5 500
param set-default PWM_AUX_DIS6 500
param set-default PWM_AUX_DIS7 500
param set-default PWM_AUX_DIS8 500

# servo 1. left shoulder
param set-default CA_SV_CS0_TYPE 19
param set-default CA_SV_CS0_TRQ_P 0.5
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS0_TRQ_Y -0.5
param set-default CA_SV_CS0_TRIM 0
# servo 2. left wrist
param set-default CA_SV_CS1_TYPE 20
param set-default CA_SV_CS1_TRQ_P 0.5
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS1_TRQ_Y -0.5
param set-default CA_SV_CS1_TRIM 0
# servo 3. right shoulder
param set-default CA_SV_CS2_TYPE 21
param set-default CA_SV_CS2_TRQ_P 0.5
param set-default CA_SV_CS2_TRQ_R 0.5
param set-default CA_SV_CS2_TRQ_Y -0.5
param set-default CA_SV_CS2_TRIM 0
# servo 4. right wrist
param set-default CA_SV_CS3_TYPE 22
param set-default CA_SV_CS3_TRQ_P 0.5
param set-default CA_SV_CS3_TRQ_R 0.5
param set-default CA_SV_CS3_TRQ_Y -0.5
param set-default CA_SV_CS3_TRIM 0
# servo 5. tail pitch
param set-default CA_SV_CS4_TYPE 23
param set-default CA_SV_CS4_TRQ_P 0.5
param set-default CA_SV_CS4_TRQ_R 0.5
param set-default CA_SV_CS4_TRQ_Y -0.5
param set-default CA_SV_CS4_TRIM 0
# servo 6. tail roll
param set-default CA_SV_CS5_TYPE 24
param set-default CA_SV_CS5_TRQ_P 0.5
param set-default CA_SV_CS5_TRQ_R 0.5
param set-default CA_SV_CS5_TRQ_Y -0.5
param set-default CA_SV_CS5_TRIM 0
# servo 7. left tail extend
param set-default CA_SV_CS6_TYPE 25
param set-default CA_SV_CS6_TRQ_P 0.5
param set-default CA_SV_CS6_TRQ_R 0.5
param set-default CA_SV_CS6_TRQ_Y -0.5
param set-default CA_SV_CS6_TRIM 0
# servo 8. right tail extend
param set-default CA_SV_CS7_TYPE 26
param set-default CA_SV_CS7_TRQ_P 0.5
param set-default CA_SV_CS7_TRQ_R 0.5
param set-default CA_SV_CS7_TRQ_Y -0.5
param set-default CA_SV_CS7_TRIM 0

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_AUX_FUNC1 201
param set-default PWM_AUX_FUNC2 202
param set-default PWM_AUX_FUNC3 203
param set-default PWM_AUX_FUNC4 204
param set-default PWM_AUX_FUNC5 205
param set-default PWM_AUX_FUNC6 206
param set-default PWM_AUX_FUNC7 207
param set-default PWM_AUX_FUNC8 208
